version: "3.2"

services:
  apache:
    restart: "no"
    build: 
      context: ./web
    depends_on:
      - mysql
    networks:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: ${DOCROOT}
        target: /var/www/html/
        consistency: cached
      #- ${DOCROOT}:/var/www/html/:cached
      #- localwebdev-docroot-sync:/var/www/html:nocopy # nocopy is important

  

  mysql:
    restart: "no"
    image: mariadb:${MYSQL_VERSION:-latest}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:

      - ./mysql/:/var/lib/mysql:delegated
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    #container_name: "${MYSQLDB_NAME}"

volumes:
  localwebdev-docroot-sync:
    external: true
  localwebdev-mysql-sync:
    external: true

networks:
  backend:
  frontend: